import { Asyncify } from "@task/types/types"
import { coreRemotes } from '@core/constants/coreRemotes'
export type CoreRemotes = typeof coreRemotes
export type CreateDirAsyncRemote = typeof coreRemotes.createDir
export type GetEntAsyncRemote = typeof coreRemotes.getEnt
export type HandshakeAsyncRemote = Asyncify<typeof coreRemotes.handshake>
export type InstallAppAsyncRemote = typeof coreRemotes.installApp
export type MaximizeAsyncRemote = Asyncify<typeof coreRemotes.maximize>
export type MinimizeAsyncRemote = Asyncify<typeof coreRemotes.minimize>
export type ReadDirAsyncRemote = typeof coreRemotes.readDir
export type ReadFileAsyncRemote = typeof coreRemotes.readFile
export type RunTaskAsyncRemote = Asyncify<typeof coreRemotes.runTask>
export type WaitTaskReadyAsyncRemote = typeof coreRemotes.waitTaskReady
export type WriteFileAsyncRemote = typeof coreRemotes.writeFile
