import { createDir } from '@core/remotes/createDir'
import { getEnt } from '@core/remotes/getEnt'
import { handshake } from '@core/remotes/handshake'
import { installApp } from '@core/remotes/installApp'
import { maximize } from '@core/remotes/maximize'
import { minimize } from '@core/remotes/minimize'
import { readDir } from '@core/remotes/readDir'
import { readFile } from '@core/remotes/readFile'
import { runTask } from '@core/remotes/runTask'
import { waitTaskReady } from '@core/remotes/waitTaskReady'
import { writeFile } from '@core/remotes/writeFile'
export const coreRemotes = { createDir, getEnt, handshake, installApp, maximize, minimize, readDir, readFile, runTask, waitTaskReady, writeFile }
